### ISSUE TITLE
可以加个联系方式请教你一下吗？谢谢

### ISSUE THREAD

**Issue by misson** [2019ZSS/HomomorphicSystem#2]

**Comment by 2019ZSS** [comment]
您好，我收到你发的信息辣，您可以加我的qq: 1033741293.
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"misson"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月13日(星期三) 上午8:53
收件人:&nbsp;"2019ZSS/HomomorphicSystem"<HomomorphicSystem@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[2019ZSS/HomomorphicSystem] 可以加个联系方式请教你一下吗？谢谢 (#2)
